### ISSUE TITLE
Reimplement and enhance the Perl-based (`unit.pl`) unit test control script in Python

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2717]
## Describe the Enhancement ##
The existing testing infrastructure for MET uses Perl to run the unit tests defined in each XML file. This task is to reimplement the `unit.pl` script in Python and also enhance it, as described below.

1. Reimplement [unit.pl](https://github.com/dtcenter/MET/blob/develop/internal/test_unit/perl/unit.pl) in Python supporting the options described in it's usage statement:
```
usage: perl/unit.pl [-log {log_file}] [-cmd] [-memchk] [-callchk] [-noexit] {test_xml}

  where:
        log: if present, write output from each test to the specified file
        cmd: if present, print the test commands but do not run them, 
               overrides -log
     memchk: if present, activate valgrind with memcheck
    callchk: if present, activate valgrind with callcheck
     noexit: if present, the unit tester will continue executing subsequent
               tests when a test fails
   test_xml: file containing the unit test(s) to perform
```
Recommend using the `lxml` Python package for parsing tests from the existing XML files since that's being used elsewhere within METplus.
2. Enhance this functionality to track and store the runtime for each test executed. Write it somewhere so that it can be easily compared from one run to the next.
3. Investigate whether memory usage can reasonably be tracked and compared in a similar way. This is desired, not required.
4. Update associated scripts in the MET repository to full replace calls to `unit.pl` with the python implementation.
5. Remove the existing `unit.pl` from the MET repo. Also inspect the [perl](https://github.com/dtcenter/MET/tree/develop/internal/test_unit/perl) directory and remove other scripts that are not actually being used. Ideally, the entire perl directory would be removed for the MET-12.0.0 release. 

### Time Estimate ###
2 weeks? But please update as needed.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed at this time.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No direct impacts to other repositories at this time.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: feature_2717_convert_unit.pl_to_unit.py
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
